version: '3.1'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566-4597:4566-4597'
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3,cloudformation,sts,dynamodb,ssm,secretsmanager,sns,sqs,apigateway
      - LAMBDA_EXECUTOR=local
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
