service: newsletter-api

frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: ${self:custom.defaults.lambda.runtime}
  stage: ${self:custom.defaults.stage}
  region: ${self:custom.defaults.region}
  tracing:
    lambda: true
  webpack:
    webpackConfig: ./webpack.config.js

custom:
  base: ${self:service}-${self:provider.stage}
  defaults: ${file(./defaults/sls.yml):defaults}

functions:
  subscribe:
    handler: src/handlers/subscribe.handler
    timeout: ${self:custom.defaults.lambda.timeout}
    memorySize: ${self:custom.defaults.lambda.memorySize}
    events:
      - http:
          path: /subscribe
          method: GET
    iamRoleStatements:
      - Effect: Allow
        Action:
          - xray:PutTraceSegments
          - xray:PutTraceSegments
          - xray:PutTraceSegment
          - xray:PutTelemetryRecords
          - xray:GetSamplingRules
          - xray:GetSamplingTargets
          - xray:GetSamplingStatisticSummaries
        Resource: '*'
