service: newsletter-api

frameworkVersion: '3'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: ${self:custom.defaults.lambda.runtime}
  stage: ${self:custom.defaults.stage}
  region: ${self:custom.defaults.region}

custom:
  base: ${self:service}-${self:provider.stage}
  defaults: ${file(./defaults/sls.yml):defaults}

functions:
  subscribe:
    handler: src/handlers/subscribe.handler
    timeout: ${self:custom.defaults.lambda.timeout}
    memorySize: ${self:custom.defaults.lambda.memorySize}
    events:
      - http:
          path: /subscribe
          method: GET
